# Kubernetes Manifests for Local & AWS

---
apiVersion: v1
kind: Namespace
metadata:
  name: tucoach-ai

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tucoach-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/tucoach-ai-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tucoach-secrets
                  key: openai

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: tucoach-ai
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: tucoach-secrets
  namespace: tucoach-ai
stringData:
  openai: "your-openai-api-key"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tucoach-ingress
  namespace: tucoach-ai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: tucoach.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
