# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tucoach-ai
nodes:
  - role: control-plane
  - role: worker

# After saving this file, run:
# kind create cluster --config kind-config.yaml
